---
env: 'kovan'

frontend:
  supportedNetworkName: 'the Kovan testnet'
  supportedNetwork: 42

snarkUrls:
  circuit: "https://oneofus.blob.core.windows.net/snarks/circuit.json"
  provingKey: "https://oneofus.blob.core.windows.net/snarks/proving_key.bin"

chain:
  url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
  chainId: 42
  semaphoreTreeDepth: 12 
  deployKeyPath: '/home/di/SU_KOVAN_DEPLOY_KEY'
  contracts:
    MiMC: "0x1AB6e2B57C2B732A35D4566acbD1E2DcB331F415"
    Semaphore: "0xD4f3712EC711ab9d4e3E1D6181dED12349Fe68d9"
    SemaphoreClient: "0x891B4e5C7ba61A44e0cd0D51D62b12D65f42b287"
